# Generated by Django 3.2 on 2021-08-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
