# Generated by Django 3.2 on 2021-08-18 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0003_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('myFriends', models.ManyToManyField(blank=True, related_name='myFriends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiverFriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverFriend', to='chats.profile')),
                ('senderFriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderFriend', to='chats.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageValue', models.CharField(max_length=1000)),
                ('msgStatus', models.CharField(default='unread', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('messageReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageReceiver', to='chats.profile')),
                ('messageSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageSender', to='chats.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(blank=True, default=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
